application: worldintwelve
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: /images/logo_mini.png
  upload: /images/logo_mini\.png

- url: /((en|ja)/)?
  script: handlers.main.app

- url: /(en|ja)/cities(/(|sanfrancisco|newyork|toronto|riodejaneiro|london|stockholm|munich|paris|barcelona|istanbul|melbourne|bangkok|tokyo))?
  script: handlers.citiesprojects.app

- url: /(en|ja)/projects(/)?.*
  script: handlers.citiesprojects.app

- url: /(en|ja)/matrix/.*
  script: handlers.matrix.app

- url: /(en|ja)/twelve_questions/.*
  script: handlers.single_project.app

- url: /(en|ja)/misc/.*
  script: handlers.single_project.app

- url: /(en|ja)/about(/(|cities|projects|whatis|faq|rules|team))?
  script: handlers.about.app

- url: /(en|ja)/people
  script: handlers.main.app

- url: /(en|ja)/sponsors
  script: handlers.main.app

- url: /tac
  script: handlers.main.app

- url: /(en|ja)/test_city_tokyo
  script: handlers.main.app

- url: /(en|ja)/coming_soon
  script: handlers.main.app

# For Ad test
- url: /ad
  script: handlers.main.app

# Static directories.
- url: /images
  static_dir: images

- url: /styles
  static_dir: styles/css

# This should be always at the end of the handler definitions.
- url: /.*
  script: handlers.not_found.app
