application: worldintwelve
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: /images/logo_mini.png
  upload: /images/logo_mini\.png

- url: /((en|ja)/)?
  script: main.app

- url: /((en|ja)/)?cities(/(|sanfrancisco|newyork|toronto|riodejaneiro|london|stockholm|munich|paris|barcelona|istanbul|melbourne|bangkok|tokyo))?
  script: citiesprojects.app

- url: /(en|ja)/projects(/(|musicians|soundscape|treasure_box|live|dates1|dates2|grandma_cooking|micro_guide|misc|twelve_questions|bck|marketplace))?
  script: citiesprojects.app

- url: /(en|ja)/project_matrix/.*
  script: projectmatrix.app

- url: /(en|ja)/about(/(|cities|projects|whatis|faq|rules|team))?
  script: about.app

- url: /(en|ja)/people
  script: main.app

- url: /(en|ja)/sponsors
  script: main.app

- url: /tac
  script: main.app

- url: /(en|ja)/test_city_tokyo
  script: main.app

- url: /(en|ja)/coming_soon
  script: main.app

# Static directories.
- url: /images
  static_dir: images

- url: /styles
  static_dir: styles/css

# This should be always the end of the handler definitions.
- url: /.*
  script: not_found.app
